let conexion; 

conexion =db.getSiblingDB('instituto')

conexion.estudiante.insertMany([
  {
    nombre: "Juan",
    apellido: "Pérez",
    edad: 20,
    sexo: "Masculino",
    correo: "juan.perez@email.com",
    telefono: "555-1001",
    direccion: { ciudad: "Ciudad de México", estado: "CDMX", pais: "México" },
    carrera: "Ingeniería en Sistemas",
    semestre: 4,
    promedio: 8.7,
    fecha_inscripcion: new Date("2022-08-15"),
    activo: true
  },
  {
    nombre: "María",
    apellido: "Gómez",
    edad: 22,
    sexo: "Femenino",
    correo: "maria.gomez@email.com",
    telefono: "555-1002",
    direccion: { ciudad: "Guadalajara", estado: "Jalisco", pais: "México" },
    carrera: "Administración de Empresas",
    semestre: 6,
    promedio: 9.1,
    fecha_inscripcion: new Date("2021-08-20"),
    activo: true
  },
  {
    nombre: "Carlos",
    apellido: "Ramírez",
    edad: 19,
    sexo: "Masculino",
    correo: "carlos.ramirez@email.com",
    telefono: "555-1003",
    direccion: { ciudad: "Monterrey", estado: "Nuevo León", pais: "México" },
    carrera: "Contaduría",
    semestre: 2,
    promedio: 8.3,
    fecha_inscripcion: new Date("2023-01-10"),
    activo: true
  },
  {
    nombre: "Ana",
    apellido: "López",
    edad: 21,
    sexo: "Femenino",
    correo: "ana.lopez@email.com",
    telefono: "555-1004",
    direccion: { ciudad: "Puebla", estado: "Puebla", pais: "México" },
    carrera: "Psicología",
    semestre: 5,
    promedio: 9.4,
    fecha_inscripcion: new Date("2021-08-18"),
    activo: true
  },
  {
    nombre: "Luis",
    apellido: "Martínez",
    edad: 23,
    sexo: "Masculino",
    correo: "luis.martinez@email.com",
    telefono: "555-1005",
    direccion: { ciudad: "Tijuana", estado: "Baja California", pais: "México" },
    carrera: "Derecho",
    semestre: 8,
    promedio: 8.9,
    fecha_inscripcion: new Date("2020-08-12"),
    activo: true
  },
  {
    nombre: "Sofía",
    apellido: "Hernández",
    edad: 20,
    sexo: "Femenino",
    correo: "sofia.hernandez@email.com",
    telefono: "555-1006",
    direccion: { ciudad: "León", estado: "Guanajuato", pais: "México" },
    carrera: "Medicina",
    semestre: 3,
    promedio: 9.6,
    fecha_inscripcion: new Date("2022-08-22"),
    activo: true
  },
  {
    nombre: "Miguel",
    apellido: "Torres",
    edad: 24,
    sexo: "Masculino",
    correo: "miguel.torres@email.com",
    telefono: "555-1007",
    direccion: { ciudad: "Querétaro", estado: "Querétaro", pais: "México" },
    carrera: "Arquitectura",
    semestre: 9,
    promedio: 8.5,
    fecha_inscripcion: new Date("2019-08-15"),
    activo: false
  },
  {
    nombre: "Valeria",
    apellido: "Flores",
    edad: 18,
    sexo: "Femenino",
    correo: "valeria.flores@email.com",
    telefono: "555-1008",
    direccion: { ciudad: "Mérida", estado: "Yucatán", pais: "México" },
    carrera: "Diseño Gráfico",
    semestre: 1,
    promedio: 9.0,
    fecha_inscripcion: new Date("2024-01-15"),
    activo: true
  },
  {
    nombre: "Diego",
    apellido: "Sánchez",
    edad: 22,
    sexo: "Masculino",
    correo: "diego.sanchez@email.com",
    telefono: "555-1009",
    direccion: { ciudad: "Toluca", estado: "Estado de México", pais: "México" },
    carrera: "Ingeniería Industrial",
    semestre: 7,
    promedio: 8.1,
    fecha_inscripcion: new Date("2021-01-10"),
    activo: true
  },
  {
    nombre: "Fernanda",
    apellido: "Castillo",
    edad: 21,
    sexo: "Femenino",
    correo: "fernanda.castillo@email.com",
    telefono: "555-1010",
    direccion: { ciudad: "Chihuahua", estado: "Chihuahua", pais: "México" },
    carrera: "Comunicación",
    semestre: 5,
    promedio: 9.3,
    fecha_inscripcion: new Date("2021-08-25"),
    activo: true
  },
  {
    nombre: "Andrés",
    apellido: "Morales",
    edad: 23,
    sexo: "Masculino",
    correo: "andres.morales@email.com",
    telefono: "555-1011",
    direccion: { ciudad: "San Luis Potosí", estado: "San Luis Potosí", pais: "México" },
    carrera: "Economía",
    semestre: 8,
    promedio: 8.6,
    fecha_inscripcion: new Date("2020-01-15"),
    activo: true
  },
  {
    nombre: "Daniela",
    apellido: "Ortiz",
    edad: 19,
    sexo: "Femenino",
    correo: "daniela.ortiz@email.com",
    telefono: "555-1012",
    direccion: { ciudad: "Aguascalientes", estado: "Aguascalientes", pais: "México" },
    carrera: "Enfermería",
    semestre: 2,
    promedio: 9.2,
    fecha_inscripcion: new Date("2023-08-10"),
    activo: true
  },
  {
    nombre: "Ricardo",
    apellido: "Vega",
    edad: 25,
    sexo: "Masculino",
    correo: "ricardo.vega@email.com",
    telefono: "555-1013",
    direccion: { ciudad: "Cancún", estado: "Quintana Roo", pais: "México" },
    carrera: "Turismo",
    semestre: 10,
    promedio: 8.4,
    fecha_inscripcion: new Date("2019-01-10"),
    activo: false
  },
  {
    nombre: "Paula",
    apellido: "Rojas",
    edad: 20,
    sexo: "Femenino",
    correo: "paula.rojas@email.com",
    telefono: "555-1014",
    direccion: { ciudad: "Morelia", estado: "Michoacán", pais: "México" },
    carrera: "Biología",
    semestre: 4,
    promedio: 9.5,
    fecha_inscripcion: new Date("2022-01-15"),
    activo: true
  },
  {
    nombre: "Jorge",
    apellido: "Navarro",
    edad: 22,
    sexo: "Masculino",
    correo: "jorge.navarro@email.com",
    telefono: "555-1015",
    direccion: { ciudad: "Hermosillo", estado: "Sonora", pais: "México" },
    carrera: "Ingeniería Mecánica",
    semestre: 6,
    promedio: 8.2,
    fecha_inscripcion: new Date("2021-08-16"),
    activo: true
  },
  {
    nombre: "Camila",
    apellido: "Silva",
    edad: 21,
    sexo: "Femenino",
    correo: "camila.silva@email.com",
    telefono: "555-1016",
    direccion: { ciudad: "Culiacán", estado: "Sinaloa", pais: "México" },
    carrera: "Marketing",
    semestre: 5,
    promedio: 9.1,
    fecha_inscripcion: new Date("2021-01-20"),
    activo: true
  },
  {
    nombre: "Alejandro",
    apellido: "Cruz",
    edad: 24,
    sexo: "Masculino",
    correo: "alejandro.cruz@email.com",
    telefono: "555-1017",
    direccion: { ciudad: "Villahermosa", estado: "Tabasco", pais: "México" },
    carrera: "Ingeniería Civil",
    semestre: 9,
    promedio: 8.8,
    fecha_inscripcion: new Date("2019-08-14"),
    activo: true
  },
  {
    nombre: "Natalia",
    apellido: "Mendoza",
    edad: 18,
    sexo: "Femenino",
    correo: "natalia.mendoza@email.com",
    telefono: "555-1018",
    direccion: { ciudad: "Durango", estado: "Durango", pais: "México" },
    carrera: "Veterinaria",
    semestre: 1,
    promedio: 9.7,
    fecha_inscripcion: new Date("2024-08-12"),
    activo: true
  },
  {
    nombre: "Fernando",
    apellido: "Guerrero",
    edad: 23,
    sexo: "Masculino",
    correo: "fernando.guerrero@email.com",
    telefono: "555-1019",
    direccion: { ciudad: "Oaxaca", estado: "Oaxaca", pais: "México" },
    carrera: "Historia",
    semestre: 7,
    promedio: 8.9,
    fecha_inscripcion: new Date("2020-08-18"),
    activo: true
  },
  {
    nombre: "Lucía",
    apellido: "Reyes",
    edad: 22,
    sexo: "Femenino",
    correo: "lucia.reyes@email.com",
    telefono: "555-1020",
    direccion: { ciudad: "La Paz", estado: "Baja California Sur", pais: "México" },
    carrera: "Relaciones Internacionales",
    semestre: 6,
    promedio: 9.0,
    fecha_inscripcion: new Date("2021-01-18"),
    activo: true
  }
]);
